typography_spectrum: 0.020548725500702858
color:
  brandStrength: 0.5427872890140861
  lightness: 0.4308263848070055
  saturation: 0.7735383382532746
  rhythmicContrast: 0.8473406771663576
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.8603383044246584
author:
  name: lolo rodriguez
  email: lolorodriguez@me.com
  url: 'http://lolorodriguez.net'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3bde55d6-bbfd-4143-9d62-13dc9ce0a40f.png
name: lolo rodriguez
title: loló rodriguez
description: artista visual
